### ISSUE TITLE
Profile pictures in chats 

### ISSUE THREAD

**Issue by MadHodrick** [OverstepCo/ConnectApp#31]
Currently, chats are not displaying profile pictures correctly. They need to be switched over to the new system

**Comment by MadHodrick** [comment]
Fixed this. However, the icons are slightly offset this is most likely due to something in the CSS so it's out of my expertise.

**Comment by jadasi** [comment]
I don't see an issue. Was it fixed?

**Comment by MadHodrick** [comment]
Yeah I guess it was fixed. Dont know where tho
