### ISSUE TITLE
Dynamically load member groups of the school into lists.

### ISSUE THREAD

**Issue by MadHodrick** [OverstepCo/ConnectApp#6]
The code on line 237 of prints out the users name it just needs to be added to the html. I tryed to add this and i just kept on braking things

**Comment by jadasi** [comment]
Here is a list of where we need it:
- [x] Home Page (school members list)
- [x] Profile Page (friend list)
- [x] Events Page (RSVP list)
- [x] New Event Page (School members list)
- [x] New Chat Page (School members list)
- [x] Chat Room Pages (chat members)

**Comment by MadHodrick** [comment]
got rsvp to work but need to setup un-rsvp

**Comment by MadHodrick** [comment]
finished loading all the specified areas. need to upgrade some of them to use the new Username system
